version: "3"

services:
  aria2-rclone:
    image: johnshh/aria2-rclone
    ports:
      - "6800:6800"
      - "6880:80"
    volumes:
      - ./rclone:/root/.config/rclone
      - ./data:/aria2/downloads
    environment:
      - SECRET=hello
    restart: unless-stopped
  filebrowser:
    image: filebrowser/filebrowser
    ports:
      - "80:80"
    volumes:
      - ./data:/srv
    restart: unless-stopped
